BehinQueryApp/Pages/Accounts/SignOut.cshtml.cs
using _0_FrameWork.FW.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BehinQueryApp.Pages.Accounts
{
    public class SignOutModel : PageModel
    {
        private readonly IAuthHelper _authHelper;

        public SignOutModel(IAuthHelper authHelper)
        {
            _authHelper = authHelper;
        }

        public IActionResult OnGet()
        {
            _authHelper.SignOut();
            return RedirectToPage("/");
        }
    }
}

BehinQueryApp/Pages/Accounts/Signing.cshtml.cs
using AccountManagement.Application.Contract.UserCon;
using AccountManagement.Application.Contract.UserCon.ViewModel.Request;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BehinQueryApp.Pages.Accounts
{
	public class SigningModel : PageModel
    {
        public User_Login_Request request;

        private readonly IUserApplication _application;

        public SigningModel(IUserApplication application)
        {
            _application = application;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(User_Login_Request request)
        {
            await _application.LoginAsync(request);
            return Redirect("../Index");
        }


    }
}

BehinQueryApp/Pages/Accounts/signup.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using AccountManagement.Application.Contract.UserCon.ViewModel.Request;
using AccountManagement.Application.Contract.UserCon;

namespace BehinQueryApp.Pages.Accounts
{
	public class signupModel : PageModel
	{

		public User_Register_Request request;

		private readonly IUserApplication _application;

		public signupModel(IUserApplication application)
		{
			_application = application;
		}

		public void OnGet()
        {
        }

		public async Task<IActionResult> OnPostAsync(User_Register_Request request)
		{
			await _application.RegisterAsync(request);
			return Redirect("./Signing");
		}

	}
}

BehinQueryApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BehinQueryApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

BehinQueryApp/Pages/Index.cshtml.cs
using _01_FrameWork.QueryCommand;
using BehinQueryApp.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BehinQueryApp.Pages
{
	[Authorize]
	public class IndexModel : PageModel
    {
        private readonly IQueryCommandSession _queryCommandSession;
        private readonly IQueryCmdAdo _queryCmdAdo;  
		public IndexModel(IQueryCommandSession queryCommandSession,IQueryCmdAdo queryCmdAdo)
        {
            this._queryCommandSession = queryCommandSession;
            _queryCmdAdo = queryCmdAdo;
        }

        public void OnGet()
        {

        }
       
        public IActionResult OnPost(string ConnectionString)
        {
            if (string.IsNullOrEmpty(ConnectionString))
                return Redirect("/NotFound");

			_queryCommandSession.SetConnectionString(ConnectionString);
			var tblName=_queryCmdAdo.GetTableName();

            if(tblName is null)
				return Redirect("/NotFound");

			
            return Redirect("https://localhost:7009/QueryCommand");
        }
    }
}

BehinQueryApp/Pages/NotFound.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BehinQueryApp.Pages
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BehinQueryApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BehinQueryApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

BehinQueryApp/Pages/QueryCommand/Index.cshtml.cs
using BehinQueryApp.Model.QueryCommandAgg;
using BehinQueryApp.Service.QueyCommand.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BehinQueryApp.Pages.QueryCommand
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IQueryCommandRepository _repository;
        private readonly IQueryCommandAdoRepository _adoRepository;
        private readonly IQueryCommandLogRepository _commandLogRepository;
        
        public IndexModel(IQueryCommandRepository repository, IQueryCommandAdoRepository queryCommandAdoRepository,
            IQueryCommandLogRepository queryCommandLogRepository)
        {
            _repository = repository;
            _adoRepository = queryCommandAdoRepository;
            _commandLogRepository = queryCommandLogRepository;
        }
        public Search_QueryCommand_Command search;
        public List<GetAll_QueryCommand_Query> Queries;
        public void OnGet(Search_QueryCommand_Command search)
        {
            Queries = _repository.GetAllAsync(search).Result;
        }
        public IActionResult OnGetCreate()
        {
            return Partial("./Create");
        }

        public async Task<JsonResult> OnPostCreateAsync(Create_QueryCommand_Command command)
        {
            var res = await _repository.CreateAsync(command);
            return new JsonResult(res);
        }
        public IActionResult OnGetEdit(long id)
        {
            var res = _repository.GetAsync(id).Result;
            return Partial("./Edit", res);
        }


        public JsonResult OnPostEdit(Edit_QueryCommand_Command command)
        {
            var resualt = _repository.EditAsync(command).Result;
            return new JsonResult(resualt);
        }

        public IActionResult OnGetViewAll(long id)
        {
            var res = _repository.GetAsync(id).Result;
            return Partial("./ViewAll", res);
        }
        public IActionResult OnGetActive(long id)
        {
            var res = _repository.ActiveAsync(id).Result;
            return Redirect("QueryCommand");
        }
        public IActionResult OnGetDeActive(long id)
        {
            var res = _repository.DeActiveAsync(id).Result;
            return RedirectToAction("QueryCommand");
        }
        public IActionResult OnGetExecute(long id)
        { 
            var res = _adoRepository.ExecuteQueryAsync(id).Result;
            
            return Partial("./ExcuteResualt", res);
        }
        public IActionResult OnPostExcuteEdit(string querycmd)
        {
            var res = _adoRepository.ExecuteQueryAsync(querycmd).Result;
            return Partial("ExcuteResualtEdit", res);
        }

    }
}

BehinQueryApp/Pages/QueryCommandLog/Index.cshtml.cs
using BehinQueryApp.Model.QueryCommandAgg;
using BehinQueryApp.Service.QueyCommandLog.ViewModel;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BehinQueryApp.Pages.QueryCommandLog
{
	public class IndexModel : PageModel
	{
		private readonly IQueryCommandLogRepository _queryCommandLog;

		public IndexModel(IQueryCommandLogRepository queryCommandLog)
		{
			_queryCommandLog = queryCommandLog;
		}
		public List<GetAll_QueryCommandLog_Query> QueryCommandLog;

		public Search_QueryCommandLog_Command search;
		public void OnGet(Search_QueryCommandLog_Command search)
		{
			QueryCommandLog = _queryCommandLog.GetAllAsync(search).Result;
		}
	}
}

BehinQueryApp/Pages/Accounts/SignOut.cshtml
@page
@model BehinQueryApp.Pages.Accounts.SignOutModel
@{
}

BehinQueryApp/Pages/Accounts/Signing.cshtml
@page
@model BehinQueryApp.Pages.Accounts.SigningModel
@{
	ViewData["AccountTitle"] = "ورود";
	Layout = "_AccountLayout";
}
<div class="row signpages text-center">
	<div class="col-md-12">
		<div class="card">
			<div class="row row-sm">
				<div class="col-lg-6 col-xl-5 d-none d-lg-block text-center bg-primary details">
					<div class="mt-5 pt-4 p-2 pos-absolute">
						<img src="https://www.behinafzar.ir/Images/New%20image/logo_2_50.png" class="header-brand-img mb-4" alt="logo">
						<div class="clearfix"></div>
						<h5 class="mt-4 text-white">حساب کاربری برای خود بسازید</h5>
						<span class="tx-white-6 tx-13 mb-5 mt-xl-0">برای ایجاد ، کشف و ارتباط با جامعه جهانی ثبت نام کنید</span>
					</div>
				</div>
				<div class="col-lg-6 col-xl-7 col-xs-12 col-sm-12 login_form ">
					<div class="container-fluid">
						<div class="row row-sm">
							<div class="card-body mt-2 mb-2">
								<img src="/assets/img/brand/logo.png" class=" d-lg-none header-brand-img text-left float-left mb-4" alt="logo">
								<div class="clearfix"></div>
								<form method="post">
									<h5 class="text-right mb-2">به حساب خود وارد شوید</h5>
									<p class="mb-4 text-muted tx-13 ml-0 text-right">برای ایجاد ، کشف و ارتباط با جامعه جهانی وارد سیستم شوید</p>
									<div class="form-group text-right">
										<label>شماره </label>
										<input asp-for="request.Mobile" class="form-control" placeholder="شماره خود را وارد کنید" type="text">
									</div>
									<div class="form-group text-right">
										<label>کلمه عبور</label>
										<input asp-for="request.Password" class="form-control" placeholder="رمز ورود خود را وارد کنید" type="password">
									</div>
									<button class="btn ripple btn-main-primary btn-block">ورود</button>
								</form>
								<div class="text-right mt-5 ml-0">
									<div>حساب ندارید؟ <a asp-page="signup">اینجا ثبت نام کنید</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

BehinQueryApp/Pages/Accounts/signup.cshtml
@page
@model BehinQueryApp.Pages.Accounts.signupModel
@{
	

	ViewData["AccountTitle"] = "ثبت نام";
	Layout = "_AccountLayout";
}
<div class="row signpages text-center">
	<div class="col-md-12">
		<div class="card">
			<div class="row row-sm">
				<div class="col-lg-6 col-xl-5 d-none d-lg-block text-center bg-primary details">
					<div class="mt-5 pt-5 p-2 pos-absolute">
						<img src="https://www.behinafzar.ir/Images/New%20image/logo_2_50.png" class="header-brand-img mb-4" alt="logo">
						<div class="clearfix"></div>
						<h5 class="mt-4 text-white">حساب کاربری برای خود بسازید</h5>
						<span class="tx-white-6 tx-13 mb-5 mt-xl-0">برای ایجاد ، کشف و ارتباط با جامعه جهانی ثبت نام کنید</span>
					</div>
				</div>
				<div class="col-lg-6 col-xl-7 col-xs-12 col-sm-12 login_form ">
					<div class="container-fluid">
						<div class="row row-sm">
							<div class="card-body mt-2 mb-2">
								<img src="/assets/img/brand/logo.png" class=" d-lg-none header-brand-img text-left float-left mb-4" alt="logo">
								<div class="clearfix"></div>
								<h5 class="text-right mb-2">ثبت نام رایگان</h5>
								<p class="mb-4 text-muted tx-13 ml-0 text-right">ثبت نام رایگان است و فقط یک دقیقه طول می کشد.</p>
								<form method="post">
									<div class="form-group text-right">
										<label>نام</label>
										<input asp-for="request.FullName" class="form-control" placeholder="اسمت را وارد کن" type="text">
									</div>
									<div class="form-group text-right">
										<label>شماره </label>
										<input asp-for="request.Mobile" class="form-control" placeholder="شماره خود را وارد کنید" type="text">
									</div>
									<div class="form-group text-right">
										<label>کلمه عبور</label>
										<input asp-for="request.Password" class="form-control" placeholder="رمز ورود خود را وارد کنید" type="password">
									</div>
									<button class="btn ripple btn-main-primary btn-block">ایجاد حساب</button>
								</form>
								<div class="text-right mt-5 ml-0">
									<p class="mb-0">در حال حاضر یک حساب کاربری دارید <a asp-page="Signing">ورود</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

BehinQueryApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "رشته اتصال";
    Layout = "_HomeLayout";

}


<div class="page main-signin-wrapper bg-primary construction">

    <div class="container ">
        <div class="construction1 text-center details text-white">
          
            <img src="https://www.behinafzar.ir/Images/New%20image/logo_2_50.png" class="mb-5" alt="logo">
            <h4 class="text-center text-white tx-30 font-weight-bold ">اجرای مستقیم Query روی دیتابیس !</h4>
            <p class="text-white-50 tx-15">لطفا در ورودی زیر یک کانکشن استرینگ وارد کنید و سپس روی بزن بریم کلیک کنید .</p>
            <form method="post" role="form">
                <input style="direction: initial;" name="ConnectionString" type="text" class="form-control border-left-0 pr-3" placeholder="Connection String.....">

                <button class="btn ripple alert alert-primary btn-lg btn-block" style=" background-color: #d6e0ff;margin-bottom:12%;margin-top:2%">بزن بریم</button>

            </form>



        </div>
        <div class="text-center">Query Excuted<a class="text-white-50"> BehinAfzarCV </a>AmirKharazi</div>
    </div>
</div>

BehinQueryApp/Pages/NotFound.cshtml
@page
@model BehinQueryApp.Pages.NotFoundModel
@{
	ViewData["Title"] = "404";
     Layout = "_HomeLayout";
}
<div class="page main-signin-wrapper bg-primary construction">

	<div class="container ">
		<div class="construction1 text-center details text-white">
			<div class="row align-items-center">
				<div class="col-lg-12">
					<img src="https://www.behinafzar.ir/Images/New%20image/logo_2_50.png" class="mb-5" alt="logo">
					<h1 class="tx-140 mb-0">500</h1>
				</div>
				<div class="col-lg-12 ">
					<h6 class="tx-15 mt-3 mb-4 text-white-50">
						<div class="spinner-border" role="status">
							<span class="sr-only">Loading...</span>
						</div>
						</h6>
					<a href="/" class="btn ripple btn-outline-primary" style="color: white !important;">برگشت</a>
				</div>
			</div>
		</div>
	</div>

</div>

BehinQueryApp/Pages/QueryCommand/Create.cshtml
@model BehinQueryApp.Service.QueyCommand.ViewModel.Create_QueryCommand_Command


<div class="modal-header" style="direction:initial">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزودن Query جدید</h4>
</div>

<form asp-page="Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <label class="control-label">Query</label>
                <textarea asp-for="QueryCommand" style="direction:initial" placeholder="Query ..." class="form-control" id="sqlInput" rows="10" cols="50" oninput="highlightSQL()"></textarea>
                <div id="sqlOutput" class="highlighted-text" style="direction:initial"></div>
            </div>
        </div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">افزودن</button>
    </div>
</form>

BehinQueryApp/Pages/QueryCommand/Edit.cshtml
@model BehinQueryApp.Service.QueyCommand.ViewModel.GetAll_QueryCommand_Query
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش Query: @Model.QueryCmd</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="QueryCmd" class="control-label">Query</label>
                    <textarea required="" type="text" class="form-control" asp-for="QueryCmd">
                 </textarea>

                </div>
            </div>


            <input type="hidden" asp-for="Id" value="@Model.Id" />
        </div>
    </div>

    <div class="modal-footer">
        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
            <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
        </div>
    </div>
</form>

BehinQueryApp/Pages/QueryCommand/ExcuteResualt.cshtml
@model dynamic
@{
}
<div class="modal-header" style="direction:initial">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Queryنتایج</h4>
</div>

<div class="row row-sm">
    <div class="col-lg-12">
        <div class="card custom-card overflow-hidden">
            <div class="card-body">
                <div class="card custom-card">
                    <div class="card-body">
                        <div class="main-content-label mg-b-5">
                            Query فعال
                        </div>
                        <form id="editForm" asp-page="./Index" asp-page-handler="ExcuteEdit"
                              role="form"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="row row-sm">
                                <div class="col-lg">
                                    <input name="querycmd" class="form-control" value="@Model.QueryCmd" type="text">
                                </div>
                            </div>
                            <br />
                            <button type="submit" class="btn ripple btn-info btn-rounded btn-with-icon">ویرایش <i class="fe fe-excute"></i></button>
                        </form>
                    </div>
                </div>
                <div class="table-responsive" style="max-height:400px;overflow:auto;">
                    <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                        <div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="example1_length"><label><select name="example1_length" aria-controls="example1" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> موارد/صفحه</label></div></div><div class="col-sm-12 col-md-6"><div id="example1_filter" class="dataTables_filter"><label><input type="search" class="form-control form-control-sm" placeholder="جستجو کردن..." aria-controls="example1"></label></div></div></div><div class="row">
                            <div class="col-sm-12">
                                <table class="table dataTable no-footer" id="example1" role="grid" aria-describedby="example1_info">
                                    <thead>

                                        <tr role="row">
                                            @foreach (var columnName in Model.ColumnNames)
                                            {
                                                <th class="wd-20p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" activate to sort column ascending" style="width: 143.391px;">
                                                    @columnName
                                                </th>
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach (var row in Model.Data)
                                        {
                                            <tr role="row" class="odd">
                                                @foreach (var columnName in Model.ColumnNames)
                                                {
                                                    <td>@row[columnName]</td>
                                                }
                                            </tr>
                                        }




                                    </tbody>
                                </table>
                            </div>
                        </div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="example1_info" role="status" aria-live="polite">نمایش دادن 1 به 10 از 57 ورودی های</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="example1_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="example1_previous"><a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="example1_next"><a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0" class="page-link">بعدی</a></li></ul></div></div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BehinQueryApp/Pages/QueryCommand/ExcuteResualtEdit.cshtml
@model dynamic
<!DOCTYPE html>
<html>
<head>
    <style>
        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

            #customers td, #customers th {
                border: 1px solid #ddd;
                padding: 8px;
            }

            #customers tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            #customers tr:hover {
                background-color: #ddd;
            }

            #customers th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #04AA6D;
                color: white;
            }
    </style>
</head>
<body>

    <h1 style="direction: rtl;">نتیجه Query زنده</h1>

    <table id="customers">
        <tr role="row">
            @foreach (var columnName in Model.ColumnNames)
            {
                <th class="wd-20p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" activate to sort column ascending" style="width: 143.391px;">
                    @columnName
                </th>
            }
        </tr>

        @foreach (var row in Model.Data)
        {
            <tr role="row" class="odd">
                @foreach (var columnName in Model.ColumnNames)
                {
                    <td>@row[columnName]</td>
                }
            </tr>
        }
    </table>

</body>
</html>

BehinQueryApp/Pages/QueryCommand/ViewAll.cshtml
@model BehinQueryApp.Service.QueyCommand.ViewModel.GetAll_QueryCommand_Query

 <div class="modal-header" style="direction:initial">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزودن Query جدید</h4>
</div>

<form>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <label class="control-label">Query</label>
                <textarea id="sqlInput" rows="10" cols="50" style="font-weight:bold;direction:ltr;color:darkblue" asp-for="QueryCmd" disabled class="form-control">
                </textarea>

            </div>
        </div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
    </div>
</form> 

BehinQueryApp/Pages/QueryCommandLog/Index.cshtml
@page
@model BehinQueryApp.Pages.QueryCommandLog.IndexModel
@using _01_FrameWork;
@{
    
    ViewData["PanelTitle"] = "Query ها";
}
<div class="page-header">
    <div>
        <h2 class="main-content-title tx-24 mg-b-5">@ViewData["Admintitle"]</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">لاگ ها</a></li>
            <li class="breadcrumb-item active" aria-current="page">@ViewData["Admintitle"]</li>
        </ol>
    </div>

   

</div>


<!-- Row Serch With SerchModel -->
<div class="row row-sm">
    <div class="col-lg-12 col-md-12">
        <div class="card custom-card">
            <div class="card-body">
                <div>
                    <h6 class="main-content-label mb-1">
                        جستجو پیشرفته !
                    </h6>
                    <p class="text-muted card-sub-title">بر اساس این جستجو شما میتوانید برا اساس آیتم ها Query  خود را بیابید .</p>
                </div>
                <form method="get" role="form">
                    <div class="row row-sm">
                        <div class="col-lg">
                            <input name="search.UserName" class="form-control" placeholder="Query" type="text">
                        </div>

                    </div>
                    <br />
                    <button type="submit" class="btn btn-lg btn-block ripple btn-primary btn-with-icon">جستجو <i class="fe fe-search"></i></button>

                </form>

            </div>
        </div>
    </div>
</div>
<div class="row row-sm">
    <div class="col-lg-12">
        <div class="card custom-card overflow-hidden">
            <div class="card-body">
                <div>
                    <h6 class="main-content-label mb-1">جدول داده اصلی</h6>
                    <p class="text-muted card-sub-title">همانطور که در این مثال نشان داده شده است ، جستجو ، سفارش و صفحه بندی خوب بلافاصله به جدول اضافه می شود.</p>
                </div>
                <div class="table-responsive">
                    <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">

                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table dataTable no-footer" id="example1" role="grid" aria-describedby="example1_info">
                                    <thead>
                                        <tr role="row">

                                            <th class="wd-25p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="موقعیت: activate to sort column ascending" style="width: 189.5px;">
                                                #
                                            </th>

                                            <th class="wd-20p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="دفتر: activate to sort column ascending" style="width: 143.391px;">
                                                نام
                                            </th>

                                            
                                            <th class="wd-20p sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="دفتر: activate to sort column ascending" style="width: 143.391px;">
                                                تاریخ
                                            </th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.QueryCommandLog)
                                        {

                                            <tr role="row" class="odd">
                                                <td class="id">@item.Id</td>



                                                <td style="direction: ltr;">@item.UserName</td>

                                                <td style="direction: ltr;">@item.ExcuteQuery</td>

                                               
                                                
                                            </tr>

                                        }




                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BehinQueryApp/Pages/Shared/_Header.cshtml
@{
}

<!-- Main Header-->
<div class="main-header side-header sticky">
    <div class="container-fluid">
        <div class="main-header-right">
            <a class="main-header-menu-icon" href="#" id="mainSidebarToggle"><span></span></a>
        </div>

        <div class="main-header-right">
            <div class="dropdown d-md-flex">
                <a class="nav-link icon full-screen-link" href="#">
                    <i class="fe fe-maximize fullscreen-button fullscreen header-icons"></i>
                    <i class="fe fe-minimize fullscreen-button exit-fullscreen header-icons"></i>
                </a>
            </div>
            <div class="dropdown main-profile-menu">
                <div class="dropdown-menu">
                    <a class="dropdown-item">
                        <i class="fe fe-edit"></i> ویرایش نمایه
                    </a>

                    <a href="/Account/SignOut" class="dropdown-item">
                        <i class="fe fe-power"></i> خروج از سیستم
                    </a>
                </div>
            </div>
            <button class="navbar-toggler navresponsive-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4" aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="تغییر پیمایش">
                <i class="fe fe-more-vertical header-icons navbar-toggler-icon"></i>
            </button><!-- Navresponsive closed -->
        </div>
    </div>
</div>